In [8]:
import numpy as np
from scipy.signal import convolve2d

A = np.array( [[1, 0, -2, 3, 4, 1],
[2, 9, 5, 6, 0, -1],
[0, -3, 1, 3, 4, 4],
[6, 5, 2, 0, 6, 8],
[-5, 4, -3, 1, 3, -2],
[4, 1, 2, 8, 9, 7]])
B = np.array( [[-1, -1, -1],
[-1, 8, -1],
[-1, -1, -1]])
C = convolve2d(A, B, 'valid')
print(C)

[[ 68  23  30 -24]
 [-54 -19   0   6]
 [ 38   8 -17  27]
 [ 20 -47 -19 -13]]


In [9]:
import numpy as np

X = np.array([[1, 0, -2, 3, 4, 1],
              [2, 9, 5, 6, 0, -1],
              [0, -3, 1, 3, 4, 4],
              [6, 5, 2, 0, 6, 8],
              [-5, 4, -3, 1, 3, -2],
              [4, 1, 2, 8, 9, 7]])

F = np.array([[-1, -1, -1],
              [-1, 8, -1],
              [-1, -1, -1]])

stride = 1

# Get dimensions
input_height, input_width = X.shape
filter_height, filter_width = F.shape

# Compute output dimensions
output_height = (input_height - filter_height) // stride + 1
output_width = (input_width - filter_width) // stride + 1

# Initialize output array
Y = np.zeros((output_height, output_width))

# Perform convolution
for i in range(output_height):
    for j in range(output_width):
        X_sub = X[i:i+filter_height, j:j+filter_width]
        Y[i, j] = np.sum(X_sub * F)

# Print the output Y
print(Y)

[[ 68.  23.  30. -24.]
 [-54. -19.   0.   6.]
 [ 38.   8. -17.  27.]
 [ 20. -47. -19. -13.]]


In [21]:
A = np.array([[1, 0, -2],
[2, 9, 5],
[0, -3, 1]])

In [22]:
B = np.array( [[-1, -1, -1],
[-1, 8, -1],
[-1, -1, -1]])

In [23]:
print(A*B)

[[-1  0  2]
 [-2 72 -5]
 [ 0  3 -1]]


In [2]:
import torch

In [7]:
filters = torch.randn(6,3,3,3)
inputs = torch.randn(1, 3, 16, 16)
output = torch.nn.functional.conv2d(inputs, filters, bias=None, stride=2, padding=1, dilation=1, groups=1)

In [8]:
print(output.shape)

torch.Size([1, 6, 8, 8])
